### ISSUE TITLE
Some Misc Issues in Rank 0

### ISSUE THREAD

**Issue by Reto911** [datenlord/datenlord#496]
There are some relatively important issues or minor problems that can be resolved with low effort and can be prioritized:

- [x] Remove the assertion on `max_readahead` during initialization. (#505)
- [x] Remove the `fuse_read` module. The purpose of this module is to encapsulate implementors of the `AsyncRead` trait to implement the `Stream` trait. This module was implemented early in the project but has not been used and currently, `tokio` provides a native solution, so this module can be removed
- [x] Remove legacy content from the old distributed cache, i.e., the mapping from `node_id` to `ip_port` and the mapping from `volumn_info` to `node_id` in KV.
- [x] Remove the `buffer_idx` carried by each buffer in the fuse_request buffer. (#505)
- [x] Remove the `set_fuse_fd` method from the `FileSystem` trait. We no longer need and should not rely on it. Interacting with FUSE is the responsibility of the `Session`, not the specific `FileSystem`.
- [x] Remove the commented `FUSE_INITIALIZED`. (#505)
- [x] Remove the KV-based fd allocation mechanism.

**Comment by lord2anil** [comment]
i want to work on this issue please assign me

**Comment by Reto911** [comment]
> i want to work on this issue please assign me

Of course, thanks for your help. Some tasks will be solved in the currently pending PR, as commented as above, thus there is no need to solve them by other contributors. You can try to solve the rest.

**Comment by Reto911** [comment]
> Should I create a single PR for all these issues?

No, you can solve all of them in a single PR. However, please try to keep the patch size of a single PR less than about 500 lines as possible.
